name: AWS-DevOps-End-to-End-project

on:
  pull_request:
    branches:
      - '**'


  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Select what to deploy"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - s3
          - vpc
          - ec2
          - eks
          - alb


jobs:
  terraform:
    name: Terraform Deployment
    runs-on: self-hosted


    env:
      AWS_REGION: us-east-1               

    steps:
      #########################################################################
      # Checkout Repository
      #########################################################################
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #########################################################################
      # S3
      #########################################################################

      - name: Terraform Init & Validate S3
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 's3'
        run: |
          cd S3/Modules/source-modules
          terraform init
          terraform validate

      - name: Terraform Plan S3
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 's3'
        run: |
          cd S3/Modules/source-modules
          terraform plan \
            -var-file=../../TFVARS/s3-bucket.tfvars \
            -no-color

      - name: Terraform Apply S3
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 's3')
        run: |
          cd S3/Modules/source-modules
          terraform apply \
            -auto-approve \
            -var-file=../../TFVARS/s3-bucket.tfvars

      #########################################################################
      # VPC
      #########################################################################

      - name: Terraform Init & Validate VPC
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'vpc'
        run: |
          cd VPC/Source-Modules

          terraform init
          terraform validate

      - name: Terraform Plan VPC
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'vpc'
        run: |
          cd VPC/Source-Modules

          echo "Current Directory:"
          pwd

          echo "Checking TFVARS:"
          find ../../TFVARS -type f

          terraform init

          terraform plan \
            -var-file="$(pwd)/../../TFVARS/DEV/VPC/vpc.tfvars" \
            -no-color

      - name: Terraform Apply VPC
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'vpc')
        run: |
          cd VPC/Source-Modules

          terraform init

          terraform apply \
            -auto-approve \
            -var-file="$(pwd)/../../TFVARS/DEV/VPC/vpc.tfvars"

      #########################################################################
      # EC2
      #########################################################################

      - name: Terraform Init & Validate EC2
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'ec2'
        run: |
          cd EC2/Modules/source-modules
          terraform init
          terraform validate

      - name: Terraform Plan EC2
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'ec2'
        run: |
          cd EC2/Modules/source-modules
          terraform plan \
            -var-file=../../TFVARS/ec2-instance.tfvars \
            -no-color

      - name: Terraform Apply EC2
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'ec2')
        run: |
          cd EC2/Modules/source-modules
          terraform apply \
            -auto-approve \
            -var-file=../../TFVARS/ec2-instance.tfvars

      #########################################################################
      # EKS Cluster
      #########################################################################

      - name: Terraform Init & Validate EKS Cluster
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks'
        run: |
          cd EKS/Modules/source-modules/Cluster
          terraform init
          terraform validate

      - name: Terraform Plan EKS Cluster
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks'
        run: |
          cd EKS/Modules/source-modules/Cluster
          terraform plan \
            -var-file=../../../TFVARS/eks-cluster.tfvars \
            -no-color

      - name: Terraform Apply EKS Cluster
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks')
        run: |
          cd EKS/Modules/source-modules/Cluster
          terraform apply \
            -auto-approve \
            -var-file=../../../TFVARS/eks-cluster.tfvars

      #########################################################################
      # EKS Node Group
      #########################################################################

      - name: Terraform Init & Validate EKS Node Group
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks'
        run: |
          cd EKS/Modules/source-modules/eks-node-group
          terraform init
          terraform validate

      - name: Terraform Plan EKS Node Group
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks'
        run: |
          cd EKS/Modules/source-modules/eks-node-group
          terraform plan \
            -var-file=../../../TFVARS/eks-node-group.tfvars \
            -no-color

      - name: Terraform Apply EKS Node Group
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'eks')
        run: |
          cd EKS/Modules/source-modules/eks-node-group
          terraform apply \
            -auto-approve \
            -var-file=../../../TFVARS/eks-node-group.tfvars

      #########################################################################
      # ALB
      #########################################################################

      - name: Terraform Init & Validate ALB
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'alb'
        run: |
          cd ALB/Modules/source-modules
          terraform init
          terraform validate

      - name: Terraform Plan ALB
        if: github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'alb'
        run: |
          cd ALB/Modules/source-modules
          terraform plan \
            -var-file=../../TFVARS/alb.tfvars \
            -no-color

      - name: Terraform Apply ALB
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.deploy_target == 'all' || github.event.inputs.deploy_target == 'alb')
        run: |
          cd ALB/Modules/source-modules
          terraform apply \
            -auto-approve \
            -var-file=../../TFVARS/alb.tfvars